---
title: "ShapePCA_Triangle_Script"
author: "Nicolas Yun Hwan Jeong Lee"
date: "2025-10-22"
output: html_document
---
Triangle DEMO

Load(+ Install) Packages
```{r}
#Run this to install packages if not yet installed
#install.packages("rgl")
#install.packages("shapes")
#install.packages("MASS")
#install.packages("tidyverse")

#Load packages
library(rgl)
library(shapes)
library(MASS)
library(tidyverse)
```

Import data + Prepare Data
```{r}
data <- read.csv("Triangle_Data.csv")

data_list <- split(data, data$ID)
for (i in 1:length(data_list)){
  data_list[[i]] <- subset(data_list[[i]], select = -c(ID))
}
data_array <- array(unlist(data_list), dim = c(nrow(data_list[[1]]), ncol(data_list[[1]]), length(data_list)))

```

Plot the Data
```{r}
colors <- c("blue","green","red","yellow","black","blue","green","red","yellow","black","blue","green","red","yellow","black") 

ggplot(data, aes(x = x, y = y, group = ID, fill = factor(ID))) +
  geom_polygon(color = "black") +
  scale_fill_manual(values = colors) +
  coord_equal() +
  theme(legend.position = "none")

```

Compute Tangent Coords
```{r}
# For most shape analysis, you will most likely work with shapes that have more than 3 landmarks and may also be 3D.
# In those cases, it is not recommended to use Bookstein's method (bookstein2d) to compute tangent coordinates. For the triangle example, Bookstein's method works well.
# For all other cases, such as our trajectory shape analysis, we will use the residual method, which can be used with the procGPA function from the 'shapes' package.

#This is how the code would look using the procGPA function
#proc <- procGPA(data_array, scale = TRUE)
#tangent_coords <- proc$tan # For this triangle data, the residual method will result in a 6-coordinates vector (3 Landmarks x 2 Dimensions) for each shape

#Using Bookstein's method
tangent_coords <- bookstein2d(data_array)$bshpv[3,,]

#Plot the tangent coordinates(You can run this whether it is bookstein or residual)
plot(t(tangent_coords)[,1], t(tangent_coords)[,2], pch = 21, col = colors, bg = colors)

```

Do a shape PCA
```{r}
#Using procGPA method
#pc_scores <- proc$scores

#Using Bookstein's method
pca <- prcomp1(t(tangent_coords))
pc_scores <- pca$x

#Plot PC scores
plot(pc_scores[,1], pc_scores[,2], pch = 21, col = colors, bg = colors)
```

LDA analysis
```{r}
groups <- c(1,1,1,1,1,1,2,2,2,3,3,3,3,3,3) # This is just an example of how we can split shapes into groups

#For Residual Method
#lda_model <- lda(pc_scores[,1:3], groups)

#For Bookstein's Method
lda_model <- lda(pc_scores, groups)

#Compute Scores
ld_scores <- predict(lda_model)$x

#Plot LD Scores
plot(ld_scores[,1], ld_scores[,2], pch = 21, bg = groups, col = groups)
legend(2.1, 1, legend = c(1,2,3), col = c(1,2,3), fill=c(1,2,3))
```

